export enum ErrorCode {
  // Validation
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  // Auth
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED = 'ACCOUNT_LOCKED',
  REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
  REFRESH_TOKEN_REVOKED = 'REFRESH_TOKEN_REVOKED',
  EMAIL_REQUIRED = 'EMAIL_REQUIRED',
  WEAK_PASSWORD = 'WEAK_PASSWORD',
  INVALID_OR_EXPIRED_TOKEN = 'INVALID_OR_EXPIRED_TOKEN',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  // Resources
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  INVALID_CURSOR = 'INVALID_CURSOR',
  INVALID_CATEGORY = 'INVALID_CATEGORY',
  // Business
  SLOT_UNAVAILABLE = 'SLOT_UNAVAILABLE',
  BOOKING_LIMIT_EXCEEDED = 'BOOKING_LIMIT_EXCEEDED',
  // System
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
