export enum ErrorCode {
  // Validation
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  // Auth
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  // Resources
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  // Business
  SLOT_UNAVAILABLE = 'SLOT_UNAVAILABLE',
  BOOKING_LIMIT_EXCEEDED = 'BOOKING_LIMIT_EXCEEDED',
  // System
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
